import { defineConfig } from "vitest/config";
import path from "path";
import { readFileSync } from "fs";

// Derive aliases from jsconfig.json (auto-generated by sync-client-jsconfig)
// so new modules are picked up automatically without touching this file.
const jsconfig = JSON.parse(
    readFileSync(new URL("./jsconfig.json", import.meta.url)),
);
const alias = Object.fromEntries(
    Object.entries(jsconfig.compilerOptions?.paths ?? {}).map(
        ([key, [value]]) => [
            key.replace("/*", ""),
            path.resolve(__dirname, value.replace("/*", "")),
        ],
    ),
);

export default defineConfig({
    resolve: { alias },
    test: {
        environment: "jsdom",
        globals: true,
        // Client JS lives under src/ since 0.5 — there is no `assets/client/`.
        // Tests sit next to the code they cover, per aurora's co-location
        // convention for Vue/JS.
        include: ["src/**/*.{test,spec}.{js,ts}"],
        exclude: ["node_modules", "vendor"],
        // A client project legitimately starts with no frontend tests. Kept so
        // `make test-frontend` is green on an empty project — but note this
        // previously hid a dead `include` path, so if you expect tests to run
        // and see none, check the glob above before trusting the green.
        passWithNoTests: true,
        testTimeout: 30000,
        env: { TZ: "UTC" },
    },
});
