import { defineConfig } from "vitest/config";
import path from "path";
import { readFileSync } from "fs";

// Derive aliases from jsconfig.json (auto-generated by sync-client-jsconfig)
// so new modules are picked up automatically without touching this file.
const jsconfig = JSON.parse(
    readFileSync(new URL("./jsconfig.json", import.meta.url)),
);
const alias = Object.fromEntries(
    Object.entries(jsconfig.compilerOptions?.paths ?? {}).map(
        ([key, [value]]) => [
            key.replace("/*", ""),
            path.resolve(__dirname, value.replace("/*", "")),
        ],
    ),
);

export default defineConfig({
    resolve: { alias },
    test: {
        environment: "jsdom",
        globals: true,
        include: ["assets/client/**/*.{test,spec}.{js,ts}"],
        exclude: ["node_modules", "vendor"],
        passWithNoTests: true,
        testTimeout: 30000,
        env: { TZ: "UTC" },
    },
});
